#Environment Variables in Run Configurations=spring.profiles.active=ssl
#       "env": {
#        // "SPRING_PROFILES_ACTIVE": "local"
#        "SPRING_PROFILES_ACTIVE": "ssl"
#      }
spring:
  config:
    activate:
      on-profile: ssl
  kafka:
    topic: library-events
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        # see if possible to update as relative path
        trust-store-location: file:../kafka-cluster-ssl/secrets/kafka.producer.truststore.jks
        trust-store-password: confluent
        key-store-location: file:../kafka-cluster-ssl/secrets/kafka.producer.keystore.jks
        key-store-password: confluent
      properties:
        acks: all
        retries: 9 # 10
        retry.backoff.ms: 999 #1000
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:
    admin:
      properties:
        bootstrap.servers: localhost:9092
